Proyecto_templates/templates_project/templates_app/urls.py
from django.urls import path
from . import views

app_name = "templates_app"

urlpatterns = [
    path("relative/", views.relative, name="relative"),
    path("other/", views.other, name="other"),
]

Proyecto_templates/templates_project/templates_project/urls.py
from django.contrib import admin
from django.urls import path, include
from templates_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path("templates_app/", include("templates_app.urls")),
]

Proyecto_templates/templates_project/templates_app/models.py
from django.db import models

# Create your models here.

Proyecto_templates/templates_project/templates_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {"text": "hello world", "number": 100}
    return render(request, "templates_app/index.html", context_dict)

def other(request):
    return render(request, "templates_app/other.html")

def relative(request):
    return render(request, "templates_app/relative_url_templates.html")

Proyecto_templates/templates_project/templates/templates_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <title>Base HTML</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'templates_app:other' %}">Other</a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
            <!--Anything outside of this will be inherited if you extend!-->
        {% endblock %}
    </div>
</body>
</html>

Proyecto_templates/templates_project/templates/templates_app/index.html
<!DOCTYPE html>
{% extends "templates_app/base.html" %}
{% block body_block %}
<h1>Welcome to index!</h1>
<h1>This is index.html page showing!</h1>
<h1>{{text|upper}}</h1>
<h1>{{number|add:"99"}}</h1>
{% endblock %}

Proyecto_templates/templates_project/templates/templates_app/other.html
<!DOCTYPE html>
{% extends "templates_app/base.html" %}
{% block body_block %}
<h1>Welcome to other!</h1>
<h2>This is an example of template inheritance!</h2>
{% endblock %}

Proyecto_templates/templates_project/templates/templates_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Relative_url_templates</title>
</head>
<body>
    <a href="{% url 'templates_app:other' %}">Go to "other" page!</a>
</body>
</html>